### ISSUE TITLE
FRESH ISSUE IN REGISTRATION OF AGGREGATOR VIA ADMIN PAGE

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#12]
1. At time of registration, in phone number column please add (+91) before blank space (Same as username at the time of login). This will avoid confusion. Otherwise someone will add phone number with country code and someone will add phone number without country code.

2. After successful registration of Aggregator through admin portal aggregator page is not showing new registered aggregator even after 30 min. Even admin log out of application and login again, application is not showing particular registered aggregator.

3. At the time of registration, want to add new field: GPS location. It will not mandatory but it will be optional. Please check possibility of same.

**Comment by prashantgithub82** [comment]
1. At time of registration, in phone number column please add (+91) before blank space (Same as username at the time of login). This will avoid confusion. Otherwise someone will add phone number with country code and someone will add phone number without country code. **FIXED**

2. After successful registration of Aggregator through admin portal aggregator page is not showing new registered aggregator even after 30 min. Even admin log out of application and login again, application is not showing particular registered aggregator.
**IN-PROGRESS**

3. At the time of registration, want to add new field: GPS location. It will not mandatory but it will be optional. Please check possibility of same.
**This can be done in background but user will be prompted from Android app to allow GPS location and it won't be pleasant experience.**

**Comment by prashantgithub82** [comment]
2. After successful registration of Aggregator through admin portal aggregator page is not showing new registered aggregator even after 30 min. Even admin log out of application and login again, application is not showing particular registered aggregator.
**FIXED**

**Comment by 7597208625** [comment]
**ADMIN CREATES NEW AGGREGATOR**
1. Admin create new Aggregator: 
     "Aggregator" page -> "ADD" -> FIll all mandatory filled -> Approval Status - "Approved" or "Declined" -> Submit
      Application shows error as shown in below picture:
      
![WhatsApp Image 2020-11-08 at 2 09 09 PM](https://user-images.githubusercontent.com/73227626/98460625-0708e300-21cc-11eb-82c7-cb01fea923ae.jpeg)

However:
       "Aggregator" page -> "ADD" -> FIll all mandatory filled -> Approval Status - "New" -> Submit
       Application works and redirect to "Aggregator" Page. With Recently added aggregator as listed under "New" list.
       
       Now select aggregator under "New" list and change Apprval Status - "Approved" -> Submit
       Application works Ok and approved aggregator is shown in "Approved" list.

So first scenario is intentional ? (First scenario should also work. Please check.)

2. Application make user corresponding to new aggregator registered. However, there are 2 points which need improvement:
    2.1: Email id is not mandatory for aggregator. So email id should not be marked mandatory for aggregator type of user. 
    2.2: Name of the user: In aggregator creation there is only one field "Representative Name". However, in user there are two fields "First name" & "Last Name". So once approval of aggregator, there is auto generation of user in application. But name "Representative name" is mapped to "First Name" & "Last Name" is blank. So we should create two field for representative also ("First Name" & "Last Name"). It will create one to one mapping. 

![WhatsApp Image 2020-11-08 at 2 18 16 PM](https://user-images.githubusercontent.com/73227626/98460774-47b52c00-21cd-11eb-8c1f-aff1a8e30dce.jpeg)

**Comment by 7597208625** [comment]
(Addition to above query)
2. 2.1: Email id was filled by admin at the time of registration of aggregator by admin. So same email id should be there for user which was created due to registration of new aggregator. 

Please check.

**Comment by 7597208625** [comment]
3. At the time of registration, want to add new field: GPS location. It will not mandatory but it will be optional. Please check possibility of same.
This can be done in background but user will be prompted from Android app to allow GPS location and it won't be pleasant experience.

**Don't want it in background. Instead there can be field where user need to submit GPS location at the time of registration. But it is not mandatory. It will create data base of collection center**

**Comment by 7597208625** [comment]
4. Default password for user created by Admin ? 
   Tried "asdf_1234" but it does not worked. Please check.

**Comment by prashantgithub82** [comment]
3. At the time of registration, want to add new field: GPS location. It will not mandatory but it will be optional. Please check possibility of same. This can be done in background but user will be prompted from Android app to allow GPS location and it won't be pleasant experience.
Don't want it in background. Instead there can be field where user need to submit GPS location at the time of registration. But it is not mandatory. It will create data base of collection center.
**What value user is expected to add into "GPS location".** We can discuss more on this.

4. Default password for user created by Admin? Tried "asdf_1234" but it does not worked. Please check.
**We are not creating default password for this. Instead please use "Forget Password" functionality to change password.**

**Comment by 7597208625** [comment]
3. At the time of registration, want to add new field: GPS location. It will not mandatory but it will be optional. Please check possibility of same. This can be done in background but user will be prompted from Android app to allow GPS location and it won't be pleasant experience.
Don't want it in background. Instead there can be field where user need to submit GPS location at the time of registration. But it is not mandatory. It will create data base of collection center.
What value user is expected to add into "GPS location". We can discuss more on this.

**User will not enter any value. Once user click on submit GPS location application will get coordiates of the user automatically.**

Need discussion on it.

**Comment by prashantgithub82** [comment]
This has been fixed, please close the ticket...
