### ISSUE TITLE
Aggregator Self registration (From Register tab of applicaiton)

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#13]
1. Email id is still mandatory for aggregator in this mode of registration. Email id should be optional. Please make appropriate changes.

**Comment by prashantgithub82** [comment]
1. FIXED

**Comment by 7597208625** [comment]
![WhatsApp Image 2020-11-08 at 2 29 16 PM](https://user-images.githubusercontent.com/73227626/98460977-d24a5b00-21ce-11eb-9d01-544e5ff145c6.jpeg)

Issue mentioned above not fixed. Please check at your end. Still same problem.

**Comment by 7597208625** [comment]
1. This issue is repeated and notified many times. Application crashed at the time of registration of **V.S. Trading Co.**. There are main two issues regarding this user:
1.1: User can login using its mobile number. That means that there is already user registered with this mobile number. As user tried for new registration with same mobile number. So application crashed. Instead of that response there should be message that user already exist so login from your mobile number. 

1.2: If this user exist then why admin is not able to see this user in user list. **It shows that there is a major bug**. User exist in database but admin is not able to see particular user. It can be the case with other user also. Please check this. It should not be case in any circumstances.

**Comment by 7597208625** [comment]
1.3 Although admin can not see V.S. Trading Co. / Harsad patel as user, user can login using mobile no. 9377527226. So user logged in tried to update company info as below:
     Login -> Company info -> EDIT & Fill all the required detail -> Submit -> ** APPLICATION CRASHED **

     This is not matter of particular user. This is stability issue of application. Application should not crash at any moment. Please check at your end.
