### ISSUE TITLE
Driver Login for shipment

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#15]
1. OTP function has been enabled. Glad to see the same.

2. Tried two time login by OTP. Both times i have received same OTP. OTP should be random and both the time there should be different OTP. Please check.

3. Default password is there. I can login by pwd: **asdf_1234**.  For testing purpose please keep default pwd. 

4. No information in shipment tab of driver login page.  Any intransit shipment marked to particular driver is not shown in shipment page. Please check. 

5. Console for driver should be very simple and one pager. Once driver login it should automatically land on in transit shipment page where driver need to send pictures of shipment mapped with him. And in top there should be button for logoff. That's it.

**Comment by prashantgithub82** [comment]
1. **Yes, OTP is enabled.**

2. **FIXED**

3. **For testing purpose, we have disabled OTP verification currently it means, even if you put any number, it will work.**

4. **FIXED**

5. **FIXED**
