### ISSUE TITLE
SHIPMENT PAGE FOR ADMIN

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#16]
1. Admin should have power to delete wrong In transit shipment uploaded by any of the aggregator.

2. There is a problem when admin try to add shipment as shown in picture. 
      
![WhatsApp Image 2020-11-01 at 4 12 22 PM](https://user-images.githubusercontent.com/73227626/97800666-0f599f00-1c5d-11eb-8ae3-8702f7b4046a.jpeg)

     This problem occur with following flow of event:
     Home Page -> Shipment page -> Select any intransit shipment -> press back button in "In Transit" screen -> Now press "ADD" button in Shipment page

     However this problem is not there with following flow of events:
      Home Page -> shipment page -> Press "ADD" button in Shipment page
      Home Page -> Shipment page -> Select any of received shipment -> Press "Back" button in Dispatch page -> Now press "ADD" shipment in shipment page

      Please check possible reason of error.

3. Multiple driver user creation with same number. There is new driver user creation with same number with every new shipment. There can not be multiple user (in any case PIBO's, aggregators, recycler, driver) with same mobile number. 

    If any one add driver number, driver name and vehicle number in any new shipment then following cases will be there:
    A. Driver exist but with different aggregator and currently in transit: Aggregator should not be allowed to create new shipment with same driver as this driver is already carrying one shipment. He should be ask to update correct driver detail.
   B. Driver exist but with different aggregator and no in transit shipment with particular driver: It should not create a new user. instead old driver user name and other data should be updated as per current shipment details.
   C. Driver data does not exist: new driver user should be created with details mentioned in new shipment.

**Comment by prashantgithub82** [comment]
1. Admin should have power to delete wrong In transit shipment uploaded by any of the aggregator. **FIXED - Click on received button and there you will get Delete button.**

2. There is a problem when admin try to add shipment as shown in picture. **IN-PROGRESS**

3. Multiple driver user creation with same number. There is new driver user creation with same number with every new shipment. There can not be multiple user (in any case PIBO's, aggregators, recycler, driver) with same mobile number. **FIXED**

**Comment by 7597208625** [comment]
1. Admin should have power to delete wrong In transit shipment uploaded by any of the aggregator. FIXED - Click on received button and there you will get Delete button.
     **After Super admin delete any shipment, application redirect to Home page. Instead of home page application should redirect to shipment page.**

3. Tried to test point number 3 with new shipment creation but there is a new problem screenshot is attached below.
![WhatsApp Image 2020-11-02 at 1 32 54 PM](https://user-images.githubusercontent.com/73227626/97843817-ef36e800-1d0f-11eb-82ce-8fe8a4728591.jpeg)

**Comment by prashantgithub82** [comment]
**1. FIXED**

**2. FIXED**

**Comment by 7597208625** [comment]
1. Admin should have power to delete wrong In transit shipment uploaded by any of the aggregator. FIXED - Click on received button and there you will get Delete button. After Super admin delete any shipment, application redirect to Home page. Instead of home page application should redirect to shipment page.

**NOT FIXED. PLEASE CHECK. ONCE ADMIN DELETE ANY SHIPMENT, IT SHOULD REDIRECT TO "SHIPMENTS" page not to home page.**

**Comment by 7597208625** [comment]
1. Shipment creation problem for ADMIN: There is fresh problem when admin tries to create shipment. Error message popped up. picture is shown below. Please check.  **Earlier this error was not there.**


![WhatsApp Image 2020-11-08 at 3 58 30 PM](https://user-images.githubusercontent.com/73227626/98462604-7df9a800-21db-11eb-8f80-c8c4805b33a7.jpeg)

**Comment by 7597208625** [comment]
3. Multiple driver user creation with same number. There is new driver user creation with same number with every new shipment. There can not be multiple user (in any case PIBO's, aggregators, recycler, driver) with same mobile number.

If any one add driver number, driver name and vehicle number in any new shipment then following cases will be there:
A. Driver exist but with different aggregator and currently in transit: Aggregator should not be allowed to create new shipment with same driver as this driver is already carrying one shipment. He should be ask to update correct driver detail. **New shipment creation is now allowed. But only it is showing a message "something went wrong. Please try again later". Instead of this message application should show that dirver details are incorrect.**
B. Driver exist but with different aggregator and no in transit shipment with particular driver: It should not create a new user. instead old driver user name and other data should be updated as per current shipment details. 

**If driver exist with different aggregator but not in transit then application create new shipment. Driver can also send in transit pictures. 
But user details of driver changed to picture as shown below
![WhatsApp Image 2020-11-08 at 5 07 43 PM](https://user-images.githubusercontent.com/73227626/98463913-f5800500-21e4-11eb-8cdb-60df3217b472.jpeg)

Company type changed to Admin. Company name is not there. I suggest to keep driver to keep independent of any company. Only user type driver and by default company name & type is driver. It will not create confusion. NO email id for driver.
**
C. Driver data does not exist: new driver user should be created with details mentioned in new shipment. **New driver created with new shipment creation.**

**Comment by prashantgithub82** [comment]
**PR - All mentioned issues are fixed and deployed**

**Comment by prashantgithub82** [comment]
**All mentioned issues are fixed and deployed**
