### ISSUE TITLE
SHIPMENT RECEIVE BY RECYCLER

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#17]
1. Receive date: By default shipment receive date should be date of shipment. Recycler will have option to change the shipment receive date but it can not be date older than shipment date.

2. There was problem in application while navigation through recycler version of application. All the data of recycler disappeared abruptly. In application all the fields were blank. Immediately after logout, user was not allowed to login again. it showed some error. After waiting for 5 min, recycler was allowed to login and all the data was there. It would some kind of application error. Please check it will be issue of smoothness and stability.

3. Can we give an option of master control to master user of recycler, PIBOs & Admin. Master user can choose access of some functions or modules to a particular user of that company. It can be implemented through web portal also. Not necessary through mobile application. Please check.

**Comment by prashantgithub82** [comment]
1. **Shipment receive date should be today's date not shipment date because in case shipment get received next day, then you don't shipment receive date to be same as shipment date. Currently its accepting todays date.**

2. **It should not happen, but will keep eye on this. Please let us know timing of this issue if it comes in future.**

3. **As discussed initially Role based authorization we have given based on company, but app doesn't support roles within company. We can revisit this if time permits.**

**Comment by 7597208625** [comment]
1. Shipment receive date should be today's date not shipment date because in case shipment get received next day, then you don't shipment receive date to be same as shipment date. Currently its accepting todays date.

**If I talk about today, when recycler trying to confirm shipment application is showing 11 feb 2020. He need to navigate from 11 feb 2020 to 2 November 2020. Why 11 feb 2020?   

 Shipment receive date can be shipment date also. When recycler is trying to confirm shipment so instead of 11feb 2020, it should show shipment date.  If shipment is receive 2 days or 3 days later then recycler will change date accordingly. **

![WhatsApp Image 2020-11-02 at 1 03 46 PM](https://user-images.githubusercontent.com/73227626/97841465-e217fa00-1d0b-11eb-9134-2c47507e45d2.jpeg)

3. As discussed initially Role based authorization we have given based on company, but app doesn't support roles within company. We can revisit this if time permits.
**Role based authorization is ok and good. Now i am talking about sub user for each type of company which was not discussed earlier. Lets say we have recycler JB ECOTEX LLP. In JB ECOTEX LLP Mr. X is having whole authority for purchase, unload, payment and etc. Mr. X will not be doing all task by himself. He will be having a team of 3-4 people. In team one will be looking after shipment unloading, one will be looking after payment, one will be looking after certification part and so on. SO now Mr. X does not want to give whole control to all member of his team. So here comes sub user of JB ECOTEX LLP. Mr. X master user of JB ECOTEX LLP can add sub user and can decide access of particular module or function to particular user in recycler version of application. It can be done through web app also.**

**Comment by prashantgithub82** [comment]
**1. Month and Day is getting swapped due to time-zone. We are working on this to fix it.**

**Comment by 7597208625** [comment]
1. Receive date: By default shipment receive date should be date of shipment. Recycler will have option to change the shipment receive date but it can not be date older than shipment date. **Now showing current date. which is same as shipment date. So don't know what is status. Be default it should show shipment date.**

2. There was problem in application while navigation through recycler version of application. All the data of recycler disappeared abruptly. In application all the fields were blank. Immediately after logout, user was not allowed to login again. it showed some error. After waiting for 5 min, recycler was allowed to login and all the data was there. It would some kind of application error. Please check it will be issue of smoothness and stability. **Same kind of problem occur with aggregator also. Described in different thread. It may some kind of server communication error or stability error.**

3. Phase 2. **So will not discuss now.**

**Comment by prashantgithub82** [comment]
**For 1st item - we will be discussing in call and rest all are fixed.**

**Comment by prashantgithub82** [comment]
All issues are fixed. Please close this ticket...
