### ISSUE TITLE
Certificate by Recycler

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#18]
1. In drop down list of ADD shipments, it shows in transit shipments also. it should show only shipments which are received by recycler. It transit shipment should not be shown in ADD shipment of certificate page. Please check.

**Comment by prashantgithub82** [comment]
1. In drop down list of ADD shipments, it shows in transit shipments also. it should show only shipments which are received by recycler. It transit shipment should not be shown in ADD shipment of certificate page. Please check. 
**FIXED - On certificate page, dropdown will should only those shipments which are received by that recycler.**

**Comment by 7597208625** [comment]
Prashant ji do not close these issue.

Keep each type of issue with module wise. As we are half way in testing. 

If we keep module wise issue open then it will be very easy to discuss.
