### ISSUE TITLE
PIBO REGISTRATION

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#19]
1. Registration by ADMIN

>  A. Same type or problem as registration by admin for aggregator. 
         Admin login -> PIBOs -> " ADD" button -> Fill all details -> Approval status - "Approved" or "Declined" -> Error as shown in picture
![WhatsApp Image 2020-11-08 at 5 29 47 PM](https://user-images.githubusercontent.com/73227626/98464318-0c742680-21e8-11eb-81f4-9c9d0f1ea27e.jpeg)

          Admin Login - > PIBOs -> "ADD" Button -> Fill all details -> Approval Status - "NEW" -> Successfull and redirect to PIBOs page and user listed under "New" list. Now followup same process to approve new user and it gets approved.

> B. Heading change for PIBOs page. "PBIOs" - > "PIBOs"

    
![WhatsApp Image 2020-11-08 at 5 32 09 PM](https://user-images.githubusercontent.com/73227626/98464355-683eaf80-21e8-11eb-84c2-acae84989542.jpeg)

2. Self registration:

> change company name at the time of registration "PBIOs" -> "PIBOs"
![WhatsApp Image 2020-11-08 at 5 34 12 PM](https://user-images.githubusercontent.com/73227626/98464393-a20fb600-21e8-11eb-9fc7-6ed543670b71.jpeg)

> At time of registration:
    register -> Fill user detail (First step of registration) -> Second step (fill company details) -> "Submit" -> Error as shown in picture below. Although there was no error. 

![WhatsApp Image 2020-11-08 at 5 35 55 PM](https://user-images.githubusercontent.com/73227626/98464437-ebf89c00-21e8-11eb-9a47-0aaba824ef9d.jpeg)

Second attempt without any change went through and registration completed. Please check the same.

**Comment by prashantgithub82** [comment]
All issues are fixed and for last one - seems form has been submitted before upload document loading completed.
