### ISSUE TITLE
Registration of Aggregator

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#2]
1. Please remove PAN Card & PAN number option for aggregator.

2. Address and bank detail should be modified as issue raised in registration of recycler.

3. IN case of aggregator there is no option of shipment creation. Waiting for Admin approval or something else (Please check) ?

**Comment by prashantgithub82** [comment]
1. Please remove PAN Card & PAN number option for aggregator. **Done**

2. Address and bank detail should be modified as issue raised in registration of recycler. **Done**

3. IN case of aggregator there is no option of shipment creation. Waiting for Admin approval or something else (Please check)?
**Yes, approval is required first from admin. For admin to approve any registration - Please login as admin in app -> on any company listing page (brand, vendor, recycler), all respective new registrations will be on top under "New" status. -> Click on anyone and go "Edit", change Status from New to Approve. That registration will be approved and visible under "Approved" status.**
