### ISSUE TITLE
PIBOs Purchase order.

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#20]
1. Purchase order creation by PIBOs

> Blank space why ?
   
![WhatsApp Image 2020-11-08 at 5 44 30 PM](https://user-images.githubusercontent.com/73227626/98464604-1434ca80-21ea-11eb-839e-05e15828d1b6.jpeg)

  I think blank space is created to show shipment mapped to that purchase order. It should be dynamic. If no shipment is mapped with particular purchase order then there should not be blank space & if shipments are mapped with purchase order then it should show mapped shipment. 

However in case of PIBOs module, it is not showing any of the mapped shipment to purchase order even after mapping.
![WhatsApp Image 2020-11-08 at 6 07 13 PM](https://user-images.githubusercontent.com/73227626/98465146-40057f80-21ed-11eb-94d3-ae944c97343f.jpeg)

> Please mention quantity field with unit of measurement.    **Quantity (KG)**
    Not just here, in each and every module where we are talking about quantity.

> Particular PIBOs can see purchase orders raised by other PIBOs also. Particulare PIBOs should only have access to purchase order raised by them. 

> Need correction in purchase order description. Now it is showing quantity & Type.
    It should be Marked as follows:
    **Purchase Order Number | Raised BY**
       Quantity | Type
   
![WhatsApp Image 2020-11-08 at 5 50 24 PM](https://user-images.githubusercontent.com/73227626/98464772-00d62f00-21eb-11eb-8f46-70c75a1f9e61.jpeg)

> Heading change "PurchaseOrders" -> "Purchase Orders"
![WhatsApp Image 2020-11-08 at 5 53 41 PM](https://user-images.githubusercontent.com/73227626/98464824-70e4b500-21eb-11eb-9be8-4920d7cf1c45.jpeg)

> For Purchase Order from PIBOs for a particular state, Only shipment from particular state can be mapped. As of now any shipment can be mapped for a purchase order of a particular state.

> **Quantity Tally for Purchase Order**  For a particular purchase order total shipment quantity mapped should be less than or equal to quantity mentioned in purchase order.

**Comment by 7597208625** [comment]
**ADMIN ADD PURCHASE ORDER FROM PIBOs**

I think there is some understanding mismatch for purchase order. Purchase order will be issued by PIBOs to Nirmal Vasundhara for collection & recycling of plastic. As each Aggregator send shipment so each shipment is mapped to aggregator. Similarly purchase order will be mapped to particular PIBOs. Even if admin add purchase order for recycling services, it will be from PIBOs. So when admin try to add purchase order then it should be related to particular PIBOs. 

Each PIBOs can see purchase orders issued by them only. Other purchase orders issued by other PIBOs will not be visible to that particular PIBOs.

**Comment by prashantgithub82** [comment]
**All mentioned issues are fixed. For remaining - created new defect.**
