### ISSUE TITLE
PIBOs Purchase order - There is no Type in PO

### ISSUE THREAD

**Issue by prashantgithub82** [AppGrate/RecyclingSolutions-Issues#21]
PO Listing Page: It should be Marked as follows: Purchase Order Number | Raised BY Quantity | Type

**Comment by prashantgithub82** [comment]
**There is no "Type" in Purchase Order.**

**Comment by 7597208625** [comment]
IT SHOULD BE

ORDER NUMBER | RAISED BY
QUANTITY | QUALITY

**Comment by prashantgithub82** [comment]
**Fixed**
