### ISSUE TITLE
REPEATED ISSUE OF DATABASE AND HAS BEEN NOTIFIED MANY TIMES - V.S. TRADING CO.

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#24]
There is some problem in database. I am raising this issue repeatedly. Issue closed but no resolution. 

**V.S. TRADING CO.** - Aggregator

1. This user can login with his mobile no. 9377527226 but admin cannot see any user mapped with this user id. 
    So basically there can be a user about which admin don't know. 
![WhatsApp Image 2020-11-20 at 5 05 44 PM](https://user-images.githubusercontent.com/73227626/99795957-ac1fa600-2b52-11eb-99ef-fa51650b79b6.jpeg)

2. So as user exist so after login user tried to update aggregator profile [V.S. TRADING Co.] by filling all the mandatory required details. But to surprise when user press "SUBMIT" button, application crashed. 

Please do not close this issue without my approval.

**Comment by prashantgithub82** [comment]
**1. Fixed**

**2. Fixed**
