### ISSUE TITLE
AGGREGATOR REGISTRATION

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#25]
1. Email id is still mandatory in case when **aggregator self register on application** whereas when admin register aggregator email id is not mandatory. Please check.

2. Application creates two user with same mobile number.
       First tried registration of user from admin portal. Successfully registered. 
       Now tried registration of same user (same mobile number means same user id) -> Successfully registered -> Now login using admin portal -> approve application -> User registration successfully. 
       Now try to register same user again -> Successful -> Admin get approval request

        **So THERE CAN BE MULTIPLE USER WITH SAME USER ID. PRACTICALLY IT IS NOT POSSIBLE. IF A USER IS ALREADY REGISTERED THEN THERE SHOULD BE A MESSAGE THAT USER ALREADY EXIST SO TRY TO LOGIN OR IF FORGOT PWD THEN RECOVER THE PWD.**

3. Set a default password in case user id is created by admin. It can be like there is default password. If admin create the user then that password will be applicable but if user register by register tab then password which user choose will replace default password.

4. Aggregator Self registration:
       REGISTER TAB -> Fill required Detail -> SUbmit -> Enter Pwd and login -> Fill remaining details

       **Earlier at this stage information which was submitted earlier at the time of registration was already there in this stage. But now this information is not there. PLEASE CHECK**

5. **Application Crash** 
       Registration of AGGREGATOR BY REGISTER TAB 
       REGISTER TAB -> Fill Required Detail -> Submit -> Enter pwd and login -> Fill all the details -> Press "SUBMIT" -> APPLICATION CRASHED

        **THIS ERROR WAS NOT THERE EARLIER. SO DON'T KNOW WHAT HAPPEN.**

         > 
             ![WhatsApp Image 2020-11-21 at 6 11 50 PM (1)](https://user-images.githubusercontent.com/73227626/99877559-215bab80-2c25-11eb-879b-c8c8a4662166.jpeg)
              ![WhatsApp Image 2020-11-21 at 6 11 50 PM](https://user-images.githubusercontent.com/73227626/99877560-23256f00-2c25-11eb-99f5-74b4d172e666.jpeg)

              Applicaiton crash -> LOGIN again with same user -> Add detial -> SUBMIT -> PRESS "SUBMIT" -> SUCCESSFULL

              I THINK THERE IS SOME SMALL BUG IN CODING.

**Comment by 7597208625** [comment]
![WhatsApp Image 2020-11-21 at 6 11 50 PM (1)](https://user-images.githubusercontent.com/73227626/99878852-4ef92280-2c2e-11eb-9e60-97da7beae817.jpeg)
![WhatsApp Image 2020-11-21 at 6 11 50 PM](https://user-images.githubusercontent.com/73227626/99878853-53254000-2c2e-11eb-9bac-805653647855.jpeg)

**Comment by 7597208625** [comment]
Issue number 5 is also there with registration of recycler also. 

So it will also there with registration of PIBOs. 

Please check.

**Comment by prashantgithub82** [comment]
**1. Fixed**

**2. Fixed**

**3.** This is as per design. Setting default password is very risky as all created users will have same password. New created user will get password by using "Forget Password" functionality. 

**4. Fixed**

**5. Fixed for all**

Please use app v.20 and close this once verified.

**Comment by 7597208625** [comment]
3. OK

**Comment by 7597208625** [comment]
1. OK

2. OK

4. OK
5. Ok

**Comment by 7597208625** [comment]
6. APPLICAION -> REGISTER -> Fill Required detail for registration -> Submit -> Screen asking for OTP 
     Here if press "Login" without entering OTP -> Login successful. 

      I think it is intentional for testing purpose.

**Comment by prashantgithub82** [comment]
**Yes -  this is for testing purpose only.**

**Comment by 7597208625** [comment]
Please enable OTP function in Aggregator - > Tranporter -> Recycle version

**Comment by prashantgithub82** [comment]
This has been done, so ticket can be closed.
