### ISSUE TITLE
SHIPMENT RECEIVE BY RECYCLER

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#26]
1. In receive form claim is representing INR. So it should be as follows:
    Quality Claim (INR)

    Quantity Claim (INR)

![WhatsApp Image 2020-11-21 at 7 17 34 PM](https://user-images.githubusercontent.com/73227626/99878847-41dc3380-2c2e-11eb-87fb-45f04934b68f.jpeg)

**Comment by prashantgithub82** [comment]
**Fixed - Please verify and close this.**
