### ISSUE TITLE
Certificate Upload

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#27]
1. Completed shipments are not shown in select shipment tab. Please check.

![WhatsApp Image 2020-11-21 at 7 22 21 PM](https://user-images.githubusercontent.com/73227626/99878940-e9f1fc80-2c2e-11eb-9979-6ab54aeb62da.jpeg)

**Comment by prashantgithub82** [comment]
**Fixed - Please verify and close this.**

**Comment by 7597208625** [comment]
Login from Admin portal -> certificate -> "ADD" button missing.


![WhatsApp Image 2020-11-23 at 4 46 15 PM](https://user-images.githubusercontent.com/73227626/99956132-80e3c380-2dab-11eb-8457-e3628090f759.jpeg)

**Comment by prashantgithub82** [comment]
**Its fixed now - Available in app v20.0**
