### ISSUE TITLE
COORDINATE ON PICTURE RECEIVE IN TRANSIT SHIPMENT

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#29]
![WhatsApp Image 2020-11-25 at 10 38 21 PM](https://user-images.githubusercontent.com/73227626/100260152-15e2ea00-2f6f-11eb-939b-2d895d9c7693.jpeg)

I think round circle is coordinates. 

If it is coordinates then it is not correct. 

Will we ask permission for coordinates or there is something else >

**Comment by prashantgithub82** [comment]
**Yes, this is coordinates only but earlier it was showing as (longitude, latitude) but now its been fixed and showing as (latitude, longitude) - also we have added this feature - when you tap on this, it will directly open map with exact position.**
