### ISSUE TITLE
HOME SCREEN

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#3]
1. There are two tab at home page: 
   Company info & Profile 
   What is difference between both the tab. Both are having almost same information. 
   We can Put company information like GST, PAN, CTE, CCA, BANK DETAIL, Company address, Company name in company infor. 
   IN profile it will show Company name, Representative name, designation, Email id & Phone number. 
  By this mechanism we would be able to register different person of same organisation. 
  Only one person will have authority to change master company information. 

Please check.

**Comment by prashantgithub82** [comment]
Company info is for showing company details and Profile is for user info but there was some bug in app that's why it was pointing to same page. Its been fixed now and will be available in next release. 
**Also we are moving Profile from home screen to top right corner.**

**Comment by prashantgithub82** [comment]
Company info is for showing company details and Profile is for user info but there was some bug in app that's why it was pointing to same page. Its been fixed now and will be available in next release.
**Also we are moving Profile from home screen to top right corner.**
