### ISSUE TITLE
DRIVER USER NAME ERROR (2 user with same mobile number)

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#30]
Aggregator Add shipment -> Fill all the details -> Driver Number: 7597208625 (A user which already exist) -> Shipment created.

So basically there is user already registered with user name 7597208625 as a recycler and now we have new user (driver) with same mobile number. This is a mismatch and it should be ratified.

**Comment by prashantgithub82** [comment]
**This scenario has been fixed now...**
