### ISSUE TITLE
PIBO User without any name

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#31]
There is PIBO's User without any name. 

How it is possible to register any user without any name ? 

IS it for testing or there is a bug ?

**Comment by 7597208625** [comment]
![WhatsApp Image 2020-11-25 at 10 54 11 PM](https://user-images.githubusercontent.com/73227626/100261804-4e83c300-2f71-11eb-9f13-5f07f197e837.jpeg)

**Comment by prashantgithub82** [comment]
**It was testing data, we were trying to put blank data directly into database to test some scenario. It can be closed.**
