### ISSUE TITLE
SHIPMENT LIST FORMAT

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#32]
HOME -> Shipments 

// Screen as below

![WhatsApp Image 2020-11-26 at 9 44 21 PM](https://user-images.githubusercontent.com/73227626/100373482-d977c280-3030-11eb-8ffc-f6065b16ad0a.jpeg)

There is need to change format in which list of shipment is shown (Both Intransit & Received)

Suggested SHIPMET List FORMAT
**Invoice**
Aggregator - Recycler

Exa.
INV- 043
AJEEM ENTERPRISE AND SCRAP - JB ECOTEX LLP

(Or we can shorten name of aggregator if it is long)

**Comment by prashantgithub82** [comment]
**DONE**
