### ISSUE TITLE
IN TRANSIT SHIPMENT DETAIL FOR ADMIN & RECYCLER

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#33]
ADMIN/RECYCLER LOGIN

Home Screen -> Shipment -> Select any shipment Intransit

![WhatsApp Image 2020-11-26 at 10 00 17 PM](https://user-images.githubusercontent.com/73227626/100374866-eb5a6500-3032-11eb-9e92-50be169b06c6.jpeg)

Here, admin or recycler can not check details of any of intransit shipment which has been dispatched by aggregator. Admin or recycler only has option to receive the shipment and fill remaining details. Recycler will have access to all the information only after receipt of the shipment.

Technically if aggregator dispatch the shipment then admin & respective recycler to whom shipment has been dispatched should have access to all the details of shipment so that they can verify & check all the details. So that any mistake can be notified to aggregator.

**Comment by prashantgithub82** [comment]
We have introduced option to view "dispatch" and "received" details to view these details.

**Note: There are some UI issues related to this - we'll fix into next version.**

**Comment by 7597208625** [comment]
Is there any pending issue with UI ?

Or should i close this ?

**Comment by 7597208625** [comment]
Prashant ji any comment about this issue ?

**Comment by prashantgithub82** [comment]
This has already been closed during that time only but forgot to update comment. Please close this.
