### ISSUE TITLE
SHIPMENT RECEIVE DATE BEFORE THAN SHIPMENT DATE

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#34]
SHIPMENT RECEIVE DATE CAN NOT BE OLDER THAN SHIPMENT DATE.

Shipment with invoice number 76 by SS reclaimer was dispatched on Nov 25, 2020 but it was received by recycler on October 29, 2020. Technically shipment receive date can not be older than shipment date. 

Please check and ratify error.

**Comment by prashantgithub82** [comment]
**We will discuss on Saturday call...**

**Comment by 7597208625** [comment]
SHIPMENT RECEIVE DATE IS LATER THAN SHIPMENT DATE
