### ISSUE TITLE
Adding a new tab in shipment [State of Origin]

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#39]
Some time aggregator source material from different states and supply the same to recycler. So suggesting here adding a tab of state of origin in shipment page. And default value of the same will be state of Aggregator [Please check possibility].

**Comment by prashantgithub82** [comment]
**Completed**

**Comment by 7597208625** [comment]
Wanted to check but not able to check due to Image upload issue.

**Comment by prashantgithub82** [comment]
Image upload issue was resolved. Please verify this again.
