### ISSUE TITLE
ISSUE WITH LIST OF PIBOs SCREEN

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#41]
![WhatsApp Image 2021-01-04 at 7 15 01 PM](https://user-images.githubusercontent.com/73227626/103541245-2ddc5080-4ec1-11eb-9ee7-3b50dcdc9d01.jpeg)

**Comment by 7597208625** [comment]
Same issue is there with list of aggregators. So i think this issue will be there with each user.

![WhatsApp Image 2021-01-04 at 7 16 18 PM](https://user-images.githubusercontent.com/73227626/103541422-67ad5700-4ec1-11eb-9d4c-b0eabc2124d2.jpeg)

**Comment by prashantgithub82** [comment]
This has been **FIXED**
