### ISSUE TITLE
CERTFICATION

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#42]
1. It was discussed that certification module will show pending shipments for which certificates has not been issued (Instead of draft it will be shown as pending Certificates). But as of now no pending certificate list is shown in certificate module.
![WhatsApp Image 2021-01-11 at 6 30 45 PM](https://user-images.githubusercontent.com/73227626/104186934-2545c600-543d-11eb-9b00-836acb5e9c1b.jpeg)

2. Certificate Module -> "ADD CERTIFICATE" -> Select State ("GUJARAT") -> Select Shipment -> No shipment to add. 
     I think it is bug. For completed shipment user can add certificate from this module only by selecting shipment which has been completed. But no shipment is shown for certification however certificates are pending from Gujarat States. 

![WhatsApp Image 2021-01-11 at 6 59 20 PM](https://user-images.githubusercontent.com/73227626/104188366-2841b600-543f-11eb-8dce-51bd29642a7d.jpeg)

**Comment by 7597208625** [comment]
1. Certificates are linked with Purchase Order. A Recycler will see pending certificates only if Shipments are attached to Purchase Order. There can be option where recycler can see pending shipments for which certificates are pending.

2. Admin Login -> Certificate Module -> "ADD" ->Select State -> Select Recycler ("JB ECOTEX LLP") -> Select shipment -> Admin can add shipment for which certificates are pending even without PO.
       
       ![WhatsApp Image 2021-01-11 at 7 24 24 PM](https://user-images.githubusercontent.com/73227626/104190809-a784b900-5442-11eb-8dc6-1d6311be66c1.jpeg)

    However, there is error in recycler login. Recycler Login -> Certificate Module -> "ADD" -> Select State -> Select Shipment 
     No shipment for which certificates are pending. Probably bug.
     
      ![WhatsApp Image 2021-01-11 at 6 59 20 PM](https://user-images.githubusercontent.com/73227626/104191002-ef0b4500-5442-11eb-9f6f-5b258196575f.jpeg)

3. What is allowed quantity variation in Purchase order ?
    Tried to attach 4 shipment in Test 1 Purhcase Order total quantity was around 36MT. IT shown error.
    Whereas Attached 3 shipment in Test 1 weighing around 25875KG. Quantity of Purchase order is 25000 KG. So what is variation allowed here ?

4. There is bug in Purchase order with certification mapping. 
     A. For Test 1 Purchase order added 36MT of shipment against 25 MT (Purchase order). So it showed error but a pending certificate draft was created in Certificate module.
     B. IN Test 1 Purchase Order to ratify error 25875KG shipment was added. It was accepted but a new pending certificate draft was created in Certificate module for same purchase order. IT is a bug and resolution is needed for the same.

**Comment by prashantgithub82** [comment]
**1.**  All records for PO and Certificate were corrupted so we deleted them and so no record was showing.
**2.**  FIXED
**3.**  5% Variation has been added
**4.  A & B:** We have fixed PO and Certificate related issues. It was coming due to that it seems. Please check now.

**Comment by 7597208625** [comment]
POINT NO. 1: Can we think something where recycler can see if certificates has been issued or not. Or we can add some marking in shipment list. Mark will show that certificate has been issued for this shipment.

Please check.

**Comment by prashantgithub82** [comment]
**Yes, its been done. Now on shipment list page, you can see "certificate icon" at the right side of each shipment against which certificate has been issued.**

**Comment by 7597208625** [comment]
3. Point No. 3 5% Variation is added
    Purchase Order -> EDIT -> Status change from "Accepted" to "Certificate Issued" -> Submit
    Showed error as shown below. 
    
    5% Variation should be accepted here also.

    
![WhatsApp Image 2021-01-28 at 6 46 06 PM](https://user-images.githubusercontent.com/73227626/106143883-6823cf80-6199-11eb-9943-6a231bed9b60.jpeg)

**Comment by prashantgithub82** [comment]
**3. Initially as per your suggestion we applied 5% variation on upper limit only but now its been done for lower side as well. And for PO number "PEPSI/PO/No. 3", value 27102 is actually 8% of 25000 and that's why its failing. This is not a bug.**

**Comment by 7597208625** [comment]
OK
