### ISSUE TITLE
Default Certificate Number

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#43]
By default Certificate number is Aggregator Name (Inv NO.). 

Need to keep it Blank. Recycler will fill it as per their own series. 

![WhatsApp Image 2021-01-14 at 4 06 06 PM](https://user-images.githubusercontent.com/73227626/104579901-9924e000-5682-11eb-8c99-35a15b1e85bc.jpeg)

**Comment by prashantgithub82** [comment]
Name is coming only for all pending certificates which is getting created from system and we are explicitly setting name here. But this has been set to blank at the time of Edit.

**Comment by 7597208625** [comment]
Now it is OK. 

NAME is only for pending certificate and has been set to blank at time of EDIT and to issue certificate one has to enter certificate number.

NOW..Recycler issue certificate and give certificate number. However, in purchase order certificates are shown with aggregator name and invoice number. If recycler has issued certificate with certificate number then it should be the certificate number.

![WhatsApp Image 2021-01-15 at 10 05 01 PM](https://user-images.githubusercontent.com/73227626/104753573-36187380-577e-11eb-9225-ae177ef2283d.jpeg)

**Comment by prashantgithub82** [comment]
**This has been fixed now.**

**Comment by 7597208625** [comment]
FIXED
