### ISSUE TITLE
Purchase Order: SHIPMENT COMPLETE BUT NO OPTION TO ADD CERTIFICATE - Probably a bug

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#44]
Purchase Orders Module -> PO 1|CSSPL -> Certificates (GURU MAULI ENTERPRISE(5))

Above said shipment is completed so assigned to this purchase order. It is being shown in Certificates tab that means certificate has been issued. However Certificate has not been issued and there is no option from where certificate can be added.
 
![WhatsApp Image 2021-01-14 at 4 16 06 PM](https://user-images.githubusercontent.com/73227626/104580946-e8b7db80-5683-11eb-8e8f-9b3d471a1d45.jpeg)

![WhatsApp Image 2021-01-14 at 4 15 58 PM](https://user-images.githubusercontent.com/73227626/104580964-eeadbc80-5683-11eb-99b5-6b02336e5a34.jpeg)

**Comment by prashantgithub82** [comment]
There were bug related to Pending Certificates in PO, which was causing this issue. This has been fixed now and ready for test.
