### ISSUE TITLE
Shipments for PIBOs without even linked to purchase order

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#45]
CSSPL PIBOs LOGIN -> Shipments -> 5 Shipments are shown.

But in Purchase order only 2 shipments are linked. So it might be the case that this is due to old data which were deleted. But if we have deleted old purchase order then corresponding modification in shipments should also be there. Please check.

![WhatsApp Image 2021-01-14 at 4 20 24 PM](https://user-images.githubusercontent.com/73227626/104581345-7398d600-5684-11eb-8fbb-00f77e5bc3ec.jpeg)

**Comment by prashantgithub82** [comment]
As discussed earlier PIBOs don't have access to "Shipment" menu directly. For shipment they need to go though either PO or Certificates. There were some data issue as well and everything has been fixed and will be available in next build.
