### ISSUE TITLE
WEB PORTAL - "EDIT COMPANY"

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#51]
1. Entities -> Detailed view of aggregator -> Press "View Detail" for new Aggregator (Ridhansanvi Ventures) -> Press "Edit" -> Upload error.
    Not able to upload image file as well as PDF FILE.

![EDIT COMPANY_E1](https://user-images.githubusercontent.com/73227626/127767257-6ecc13d8-5f9e-4c72-89be-09f7b5ff4388.png)

![EDIT COMPANY_E2](https://user-images.githubusercontent.com/73227626/127767263-c951b593-8b84-4a63-b0e1-a8d11d094699.png)

**Comment by prashantgithub82** [comment]
This has been fixed...
