### ISSUE TITLE
WEB PORTAL - SHIPMENT

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#52]
1. NOT ABLE TO USE "UPLOAD" FUNCTION.

SO FURTHER TESTING PENDING. PLEASE CHECK AND UPDATE.

**Comment by 7597208625** [comment]
2. Admin Portal Login -> "SHIPMENTS" -> NONE OF THE SHIPMENTS are visible. Only it is showing as searching for shipment.
    
![SHIPMENT_E1](https://user-images.githubusercontent.com/73227626/127767747-19d76c07-3eee-4f2f-b155-fbb3bfe389d0.png)


Please check

**Comment by prashantgithub82** [comment]
This has been fixed
