### ISSUE TITLE
PURCHASE ORDER : ATTACH SHIPMENT

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#56]
1. "HOME" -> "PURCHASE ORDERS" -> "NEW" -> SELECT PURCHASE ORDER -> "VIEW DETAIL" -> EDIT -> "ADD SHIPMENT"

SHIPMENT HAVING STATE OF ORIGIN SAME AS STATE OF ORIGIN MENTIONED IN PURCHASE ORDER SHOULD BE SHOWN (AS IT IS AVAILALBE IN APPLICAITON).

HOWEVER, ALL THE SHIPMENTS ARE SHOWN. 

![PO_E2](https://user-images.githubusercontent.com/73227626/129447044-69b5ddf8-2005-40e4-9a85-eca7534aed3a.png)

**Comment by prashantgithub82** [comment]
Fixed
