### ISSUE TITLE
PURCHASE ORDER: ADD CERTIFICATE

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#58]
IN PURCHASE ORDER THERE IS A HEADING WITH NAME ADD PIBOs. 

INSTEAD of PIBOs it should be ADD CERTIFICATE or CERTIFICATES.
![PO_E3](https://user-images.githubusercontent.com/73227626/129449849-272a3980-4f5f-4877-8558-3ab7143f4c3b.png)

**Comment by prashantgithub82** [comment]
Fixed
