### ISSUE TITLE
CERTIFICATES: CANNOT CHECK RECEIVE DETAIL OF THE SHIPMENTS WHICH WERE ADDED IN CERTIFICATE

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#59]
1. As per original application if select any shipment in any of the certificate, we can see all the details of that shipment i.e. Dispatch, intransit & Receive. However, in web portal it is different. 

Certificates -> Select One Certificate -> "View Detail" -> Select Shipment which was added in certificate (i.e. "Shri Hari plastic|162" for certificate number JB/GAYATRI/001) 

After selection of certificate it goes into edit mode of shipment. A user can receive the shipment over there and change the details. However in original application user can not change shipment detail by certificate route.

![CERTIFICATE_E2](https://user-images.githubusercontent.com/73227626/129450242-f38eca69-c157-43bd-9eba-dfbde66411b6.png)

Please check this issue it is important. 

We can discuss the same in length.

**Comment by prashantgithub82** [comment]
Fixed
