### ISSUE TITLE
Mandatory Email id option in case of Aggregator

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#6]
In case of aggregator, email id should not be mandatory.

**Comment by 7597208625** [comment]
There is issue with stability of application.

Application crashed at the time of registration of Aggregator.

Please check.

**Comment by 7597208625** [comment]
In case we create new user from Admin login then how user will get password. As OTP system is not working as of now. 

please check

**Comment by 7597208625** [comment]
If admin create any User then there should be option to create user id corresponding to that user. 

It is not available as of now. 

please check.

**Comment by 7597208625** [comment]
Application crashed for Approval of VS trading only as an aggregator

Please check.

**Comment by prashantgithub82** [comment]
1. In case of aggregator, email id should not be mandatory. **FIXED**

2. There is issue with stability of application. Application crashed at the time of registration of Aggregator. **FIXED**

3. In case we create new user from Admin login then how user will get password. As OTP system is not working as of now. **We'll enable OTP soon.**

4. If admin create any User then there should be option to create user id corresponding to that user. **Need more clarification. Currently user's mobile is considered as username/userid**

5. Application crashed for Approval of VS trading only as an aggregator. **FIXED**

**Comment by 7597208625** [comment]
4. Point no. 4

If admin create any user an aggregator or recycler or PBIOs then there should be auto user id creation.

**Comment by prashantgithub82** [comment]
Point no. 4. If admin create any user an aggregator or recycler or PBIOs then there should be auto user id creation.
**FIXED**

**Comment by prashantgithub82** [comment]
All issues here are fixed, so closing this bug.
