### ISSUE TITLE
ISSUE IN ADDITION OF SHIPMENT AFTER EDIT

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#60]
I have edited some of the purchase order for which shipment was assigned. After deletion of attached shipment, Tried again to add some other shipment. But to my surprise couldn't add any shipment while application can add the shipment.

Purchase Order GT001|Gayatri Plastic -> View Detail -> Edit -> "Add" Shipment:
![PO_E4](https://user-images.githubusercontent.com/73227626/130323551-5eaa6294-e7f4-45ea-9652-e1b339f47095.png)

No shipments are shown here while in application can add required shipments.

**Comment by 7597208625** [comment]
It seems that there is some issue with application.

Sometime we can see the shipment and sometime we can not see the shipment. I have attached both the screenshot for same purchase order.

![PO_E5](https://user-images.githubusercontent.com/73227626/130323705-aeb731d4-6088-473f-a131-c0e5664dce3f.png)

![PO_E6](https://user-images.githubusercontent.com/73227626/130323711-500eaba1-053d-47be-ac42-f9b2e9b7b8ca.png)

**Comment by prashantgithub82** [comment]
Fixed
