### ISSUE TITLE
Recycler LOGIN

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#8]
Shipments:

Only select shipments which are marked for particular recycler should be shown to that particular recycler. 

Can see test shipment 43jk which is not marked to JB ECOTEX in login of JB ECOTEX. 

please check.

**Comment by 7597208625** [comment]
New User Addition by Recycler:

No tag once we add new user. 

Picture sent over whats app.

Admin need to approve this new user or it will be approved automatically ?

Please check.

**Comment by 7597208625** [comment]
Recycler can not add new shipment. 

As of now recycler can add new shipment in application. 

Recycler would be able to see shipments which are marked to recycler only. 

Please check.

**Comment by prashantgithub82** [comment]
1. Shipments: Only select shipments which are marked for particular recycler should be shown to that particular recycler. Can see test shipment 43jk which is not marked to JB ECOTEX in login of JB ECOTEX. **FIXED**

2. New User Addition by Recycler: No tag once we add new user. Picture sent over what's app. **FIXED**
2.1. Admin need to approve this new user or it will be approved automatically? **Only new company will needs to be approved, users will be approved automatically.**

3. Recycler can not add new shipment. As of now recycler can add new shipment in application. Recycler would be able to see shipments which are marked to recycler only. **FIXED**
